### ISSUE TITLE
Error log: Message "Can't remove folder"

### ISSUE THREAD

**Issue by sschwarzmann** [bit-team/backintime#597]
I am getting the following error message with backintime, version **1.0.34** (the backup is encrypted):

```
[E] Can't remove folder: /tmp/backintime/<user>/1_3904/backintime/<host>/<user>/1/new_snapshot
[E] Failed to take snapshot 17.07.2016 21:26:49 !!!
```

syslog:
```
Jul 17 21:55:53  backintime (): INFO: Command "find "/tmp/backintime/<user>/1_3904/backintime/<host>/<user>/1/new_snapshot" -type d -exec chmod u+wx {} +" returns 0
Jul 17 21:55:53  backintime (): WARNING: Command "rm -rf "/tmp/backintime/<user>/1_3904/backintime/<host>/<user>/1/new_snapshot"" returns 256
Jul 17 21:55:53  backintime (): ERROR: Can't remove folder: /tmp/backintime/<user>/1_3904/backintime/<host>/<user>/1/new_snapshot
Jul 17 21:55:55  backintime (): INFO: Command "rm -rf "/tmp/backintime/<user>/1_3904/backintime/<host>/<user>/1/20160717-215553-622"" returns 0
Jul 17 21:55:55  backintime (): ERROR: Failed to take snapshot !!!
Jul 17 21:55:59  backintime (): INFO: [GnomePlugin.Systray.run] end loop
Jul 17 21:55:59  backintime (): INFO: Mountpoint /tmp/backintime/<user>/mnt/20ED4C2C/mountpoint still in use. Keep mounted

```

Previously I've accidentally removed a folder and restored via "backintime".
While restoring a huge file which I didn't need I've tried to abort the restore. XFCE reported that backintime does not respond anymore and I've selected "terminate" in my XFCE GUI.
All necessary files have been restored successfully, but since then I can't create a new backup (snapshot).

The folder **1_3904** does not exist. There is a folder **1_3880** (a link to **/tmp/backintime/<user>/mnt/20ED4C2C/mountpoint**)

The folder in "/tmp/backintime/<user>" is created only upon start of a backintime, each time with another number in the name. If "backintime" is not running there is no folder.

So the foldername created by backintime upon start and the foldername "backintime" expects for removing diverge.

**Comment by Germar** [comment]
BackInTime automatically mount the encrypted folders on start and link them with `<Profile-ID>_<PID of the mounting process>`. That's why that number always changes.

Please open BackInTime and manually run

    rm -rf "/tmp/backintime/<user>/1_<PID>/backintime/<host>/<user>/1/new_snapshot"

in Terminal. If this reports any errrors please post them back in here

**Comment by sschwarzmann** [comment]
```
$ ps aux | grep backint
<user>        8939  0.0  0.0   2276   620 ?        S    19:14   0:00 /bin/sh /usr/bin/backintime-gnome
<user>        8940  1.2  0.7 187420 60204 ?        Sl   19:14   0:00 python /usr/share/backintime/gnome/app.py
<user>        8941  0.0  0.0   4224   200 ?        Ss   19:14   0:00 ssh-agent python /usr/share/backintime/gnome/app.py
<user>        9010  0.0  0.0  11880  2772 ?        Ss   19:14   0:00 encfs --extpass=backintime-askpass /media/<user>/backup/back-in-time /tmp/backintime/<user>/mnt/20ED4C2C/mountpoint
```

So there is a folder with PID 8940 which I can delete. Only backintime tries to delete folders with PIDs that don't exist (each time I press **Backup now** a new error message with a new number appears as "last log message"). The PID backintime tries to use for the folder name is not available with "ps aux".

After I've removed that and restarted backintime, again there is a folder with the backintime PID (1_9276), this time it's not empty and I can't delete it manually. backintime, according to error log, still wants to delete another folder which does not exist (1_9507) .

Where does the PID come from?

Btw. on the backup device there is one backup folder, and I've set up two backup folders, one of them was the one I've restored previously.

**Comment by Germar** [comment]
Sorry for the confusion. Taking a snapshot will start a new process `python /usr/share/backintime/common/backintime.py`. Both the GUI process AND the take-snapshot-process create its own symlink with its own PID. So that (not existing) PID comes from the already ended take-snapshot-process.

You need to use the PID from GUI process in above command.

**Comment by sschwarzmann** [comment]
Ah that explains the PID number and why "find" returns 0.

```
$ ps aux | grep backintime
<user>       15999  0.0  0.0   2276   624 ?        S    20:51   0:00 /bin/sh /usr/bin/backintime-gnome
<user>       16000  3.8  0.7 187412 60296 ?        Sl   20:51   0:00 python /usr/share/backintime/gnome/app.py
<user>       16001  0.0  0.0   4224   200 ?        Ss   20:51   0:00 ssh-agent python /usr/share/backintime/gnome/app.py
<user>       16020  0.0  0.0  11880  2800 ?        Ss   20:51   0:00 encfs --extpass=backintime-askpass /media/<user>/backup/back-in-time /tmp/backintime/<user>/mnt/20ED4C2C/mountpoint
```

and:
```
$ rm -rf /tmp/backintime/<user>/1_16000/backintime/<host>/<user>/1/new_snapshot/
rm: cannot remove ‘/tmp/backintime/<user>/1_15837/backintime/<host>/<user>/1/new_snapshot/backup/mnt/daten/Medien/E-Books/<file>’: Directory not empty
```

"Directory not empty". Well, I'd expect **rm -rf** to ignore non-empty directories.
There are only empty directories inside the "snapshot" folder.

**Comment by Germar** [comment]
Okay, I remember we had this before. It's a problem with `encfs`. Last time the solution was to manually delete the encrypted folder directly.

Please run

    encfsctl encode /media/<user>/backup/back-in-time backintime/<host>/<user>/1/new_snapshot

after providing your encryption password this will print the encrypted path of `backintime/<host>/<user>/1/new_snapshot`. Now you can use `rm -rf` to remove that one

    rm -rf /media/<user>/backup/back-in-time/<OUTPUT_FROM_ENCFSCTL_ABOVE>

**Comment by sschwarzmann** [comment]
Right, that did the trick, and backups are working again. Thanks for your help!

**Comment by aridus** [comment]
I am trying to solve this same problem for somebody else but I am running into problems with this comamnd:
encfsctl encode /media/<user>/backup/back-in-time backintime/<host>/<user>/1/new_snapshot
(Unable to initialise encrypted filesystem - check path). For the second (backintime/<host>/<user>/1/new_snapshot) I am putting in the appropriate names but I am unsure what is required for '/media/<user>/backup/back-in-time' as this path does not exist. 
Sorry for my ignorance, but if anybody could help (Germar?), I would greatly appreciate it.
Thanks!

**Comment by Germar** [comment]
That was the path where sschwarzmann put his backup. You need to use the path from `Where to save snapshots` in Settings for this followed by `/backintime/<host>/<user>/<profile_id>/new_snapshot`.

BTW there was a typo in the [command above](https://github.com/bit-team/backintime/issues/597#issuecomment-233739019). There must be a slash `/` instead of a space between `back-in-time` and `backintime`. I fixed it...

**Comment by aridus** [comment]
Hi Germar  - many thanks - I thought that was the problem but I was confused by the fact that when I use
'encfsctl encode /medai/maxstor/backintime/malu/malu/1/new_snapshot'
I receive the response 'Unable to initialise encrypted filesystem - check path'. This occurs whether or not I use sudo. I know the path is correct because I have cd'd into it and copied the path from the command line.
If you have any further thoughts on this, please kindly let me know.

**Comment by Germar** [comment]
:man_facepalming: sorry, my fault. The space was no typo :grin:

The syntax is 
```
encfsctl encode /path/to/encrypted/folder  path/that/should/be/encrypted
```

So in your case it need to be
```
encfsctl encode /media/maxstor  backintime/malu/malu/1/new_snapshot
```
If that still does not work please make sure the file `/media/maxstor/.encfs6.xml` does exist. If not, you will find a backup in `~/.local/share/backintime/encfsconfig_backup_/`

**Comment by aridus** [comment]
Many thanks! Unfortunately I am still receiving the same error message (Unable to initialise encrypted filesystem - check path'). Checking for ~/.local/share/backintime/encfsconfig_backup_/ the folder encfsconfig_backup_ does not exist (and therefore I cannot find .encfs6.xml).
I looked at my own machine, and I do not see that folder or file.

**Comment by Germar** [comment]
But you can still see  the snapshots if you open Back in Time!? That's wired. Are you sure, `/media/maxstor` is the path from `Where to save snapshots` in Settings?

Do you use `Main Profile` or a different profile? Can you please post your config from `~/.config/backintime/config`

**Comment by aridus** [comment]
Thanks Germar. I am sure /media/maxstor is correct (as you will see in the config below, as requested), and yes, I can see the snapshots in Back in Time, and only the Main Profile is being used. 

--

global.use_flock=false
profile1.qt4.last_path=/home/malu/Documents
profile1.qt4.places.SortColumn=1
profile1.qt4.places.SortOrder=0
profile1.qt4.settingsdialog.exclude.SortColumn=1
profile1.qt4.settingsdialog.exclude.SortOrder=0
profile1.qt4.settingsdialog.include.SortColumn=1
profile1.qt4.settingsdialog.include.SortOrder=0
profile1.snapshots.automatic_backup_anacron_period=1
profile1.snapshots.automatic_backup_anacron_unit=20
profile1.snapshots.automatic_backup_day=1
profile1.snapshots.automatic_backup_mode=7
profile1.snapshots.automatic_backup_time=0
profile1.snapshots.automatic_backup_weekday=7
profile1.snapshots.backup_on_restore.enabled=true
profile1.snapshots.bwlimit.enabled=false
profile1.snapshots.bwlimit.value=3000
profile1.snapshots.check_for_changes=true
profile1.snapshots.continue_on_errors=true
profile1.snapshots.copy_links=false
profile1.snapshots.copy_unsafe_links=false
profile1.snapshots.cron.ionice=true
profile1.snapshots.cron.nice=true
profile1.snapshots.cron.redirect_stderr=false
profile1.snapshots.cron.redirect_stdout=true
profile1.snapshots.custom_backup_time=8,12,18,23
profile1.snapshots.dont_remove_named_snapshots=true
profile1.snapshots.exclude.1.value=.gvfs
profile1.snapshots.exclude.10.value=/dev/*
profile1.snapshots.exclude.11.value=/run/*
profile1.snapshots.exclude.12.value=/etc/mtab
profile1.snapshots.exclude.13.value=/var/cache/apt/archives/*.deb
profile1.snapshots.exclude.14.value=lost+found/*
profile1.snapshots.exclude.15.value=/tmp/*
profile1.snapshots.exclude.16.value=/var/tmp/*
profile1.snapshots.exclude.17.value=/var/backups/*
profile1.snapshots.exclude.18.value=.Private
profile1.snapshots.exclude.19.value=/home/malu/Documents/28_Sept_2016
profile1.snapshots.exclude.2.value=.cache/*
profile1.snapshots.exclude.3.value=.thumbnails*
profile1.snapshots.exclude.4.value=[Tt]rash*
profile1.snapshots.exclude.5.value=*.backup*
profile1.snapshots.exclude.6.value=*~
profile1.snapshots.exclude.7.value=.dropbox*
profile1.snapshots.exclude.8.value=/proc/*
profile1.snapshots.exclude.9.value=/sys/*
profile1.snapshots.exclude.bysize.enabled=false
profile1.snapshots.exclude.bysize.value=500
profile1.snapshots.exclude.size=19
profile1.snapshots.full_rsync=false
profile1.snapshots.full_rsync.take_snapshot_regardless_of_changes=false
profile1.snapshots.include.1.type=0
profile1.snapshots.include.1.value=/home/malu/Documents/Library
profile1.snapshots.include.2.type=0
profile1.snapshots.include.2.value=/home/malu/Documents/mestrado
profile1.snapshots.include.3.type=0
profile1.snapshots.include.3.value=/home/malu/Desktop
profile1.snapshots.include.size=3
profile1.snapshots.local.nocache=false
profile1.snapshots.local.password.save=false
profile1.snapshots.local.password.use_cache=true
profile1.snapshots.local_encfs.path=/media/maxstor
profile1.snapshots.log_level=3
profile1.snapshots.min_free_inodes.enabled=true
profile1.snapshots.min_free_inodes.value=2
profile1.snapshots.min_free_space.enabled=true
profile1.snapshots.min_free_space.unit=20
profile1.snapshots.min_free_space.value=1
profile1.snapshots.mode=local
profile1.snapshots.no_on_battery=false
profile1.snapshots.notify.enabled=true
profile1.snapshots.path=/media/maxstor
profile1.snapshots.path.host=malu
profile1.snapshots.path.profile=1
profile1.snapshots.path.user=malu
profile1.snapshots.preserve_acl=false
profile1.snapshots.preserve_xattr=false
profile1.snapshots.remove_old_snapshots.enabled=true
profile1.snapshots.remove_old_snapshots.unit=80
profile1.snapshots.remove_old_snapshots.value=10
profile1.snapshots.rsync_options.enabled=false
profile1.snapshots.rsync_options.value=
profile1.snapshots.smart_remove=true
profile1.snapshots.smart_remove.keep_all=2
profile1.snapshots.smart_remove.keep_one_per_day=7
profile1.snapshots.smart_remove.keep_one_per_month=24
profile1.snapshots.smart_remove.keep_one_per_week=4
profile1.snapshots.smart_remove.run_remote_in_background=false
profile1.snapshots.ssh.cipher=default
profile1.snapshots.ssh.host=
profile1.snapshots.ssh.ionice=false
profile1.snapshots.ssh.nice=false
profile1.snapshots.ssh.nocache=false
profile1.snapshots.ssh.path=
profile1.snapshots.ssh.port=22
profile1.snapshots.ssh.prefix.enabled=false
profile1.snapshots.ssh.prefix.value=PATH=/opt/bin:/opt/sbin:\$PATH
profile1.snapshots.ssh.private_key_file=
profile1.snapshots.ssh.user=malu
profile1.snapshots.use_checksum=false
profile1.snapshots.user_backup.ionice=false
profiles.version=1
qt4.last_path=/home/malu/Documents
qt4.logview.height=500
qt4.logview.width=1319
qt4.main_window.files_view.date_width=100
qt4.main_window.files_view.name_width=520
qt4.main_window.files_view.size_width=106
qt4.main_window.files_view.sort.ascending=true
qt4.main_window.files_view.sort.column=0
qt4.main_window.height=1064
qt4.main_window.main_splitter_left_w=395
qt4.main_window.main_splitter_right_w=1400
qt4.main_window.second_splitter_left_w=717
qt4.main_window.second_splitter_right_w=660
qt4.main_window.width=1801
qt4.main_window.x=530
qt4.main_window.y=292
qt4.show_hidden_files=false

**Comment by Germar** [comment]
Sorry, I'm out of ideas. Which BiT version do you use? Backup of encfs config was introduced in 1.1.0

Strange that you can browse the encrypted snapshots with BiT without having a `.encfs6.xml` in the destination folder! If that config is missing BiT should also fail to show the snapshots...

**Comment by aridus** [comment]
Many thanks Germar. The computer (not mine) uses 1.1.12.a
I have looked at my own computer (I have the same BiT version), which does not have this problem, and I do not see encfs6.xml on either of my two backup drives, nor in ~/.local/share/backintime/encfsconfig_backup_/

I ran backintime backup at the command line on the computer that has the problem, and here is the first part of the output: 

Back In Time
Version: 1.1.12.a

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Inhibit Suspend started. Reason: take snapshot
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Remove leftover 'new_snapshot' folder from last run
INFO: [qt4systrayicon] begin loop
find: ‘/media/maxstor/backintime/malu/malu/1/new_snapshot/backup/home/malu/Documents/Library/storage/KUICVU7R’: Input/output error
WARNING: Command "find "/media/maxstor/backintime/malu/malu/1/new_snapshot" -type d -exec chmod u+wx "{}" +" returns 256
rm: cannot remove '/media/maxstor/backintime/malu/malu/1/new_snapshot/backup/home/malu/Documents/Library/locate': Directory not empty

**Comment by Germar** [comment]
:joy: that profile is not encrypted at all :laughing:

Sorry I didn't recognize that in config neither. In this case please check the filesystem of the drive `fsck /dev/sdXX`

**Comment by aridus** [comment]
Hi Germar - many thanks. The drive is ntfs. Does this provide a glimmer of a solution? Many thanks again!

**Comment by Germar** [comment]
Okay, for NTFS drives please use a Windows Machine to check the drives consistence

**Comment by aridus** [comment]
Many thanks Germar. There are no Windows machines in the house. I have used gparted to check the disk and there are some errors. As this is a relatively young back up the short cut will be to format the drive as ext4, so I think I will take that route! Again, thank you for your patience!

**Comment by SarahSzabo** [comment]
@Germar I'm having a similar issue to @sschwarzmann , but I can't find a solution to it. I've run the encfsctl part without error, but what do I do with the address? There is no such path as "/media/sarah/SENTINEL/New Kubuntu Backup/98XZlS (Long text here)".

Additionally, there is an error when trying to close the program which says "can't unmount encfs /home/sara/.local/share/backintime/mnt/DB511438/ mountpoint"

**Comment by Germar** [comment]
@SarahSzabo normally just delete that path with `rm -rf [output from encfsctl]`.

Please check and repair your destination drive for errors first. You need to unmount it and run `fsck /dev/sdXX` where /dev/sdXX is the device of the drive.

If that doesn't help please post your destination path ("Where to save snapshots" in Settings) and I'll help you with the steps to remove the folder
